sudo: required

services:
    - docker

branches:
    only:
    - master

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - env
    - docker exec build git clone https://github.com/Comcast/scytale.git
    - docker exec build git clone https://github.com/Comcast/scytale.git codecovio_build
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker exec build bash -c "pushd scytale; git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge && git checkout -qf FETCH_HEAD; popd"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker exec build bash -c "pushd codecovio_build; git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge && git checkout -qf FETCH_HEAD; popd"; fi'

script:
    - docker exec build bash -c "export GOPATH=/codecovio_build && pushd codecovio_build/src && glide install && cd scytale && go build scytale && go test -race -coverprofile=coverage.txt && popd"
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "pushd scytale; ./build_rpm.sh; popd"; fi'

after_success:
    - docker exec build bash -c "pushd codecovio_build ; bash <(curl -s https://codecov.io/bash) -t 367ce3b3-857c-42f8-87f9-1140a83f3ab4; popd"
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - docker cp build:/versionno.txt .
    - BINARY_NAME=`ls x86_64/`
    - TRAVIS_TAG=`cat versionno.txt`

deploy:
  provider: releases
  prerelease: true
  api_key: $AUTH_TOKEN_BUILD
  file: x86_64/$BINARY_NAME
  skip_cleanup: true
  on:
    condition: "$TRAVIS_PULL_REQUEST = false"

